
service: kokusaibus-scraper

custom:
  defaultProfile: default
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

frameworkVersion: ">=1.4.0"

provider:
  name: aws
  profile: ${opt:profile, self:custom.defaultProfile}
  runtime: nodejs10.x
  stackName: 'kokusaibus-scraper'
  #apiName: 'kokusaibus-scraper'
  stage: prod
  region: ap-northeast-1
  memorySize: 128
  timeout: 10
  role: ${file(./serverless-env.yml):role}
  deploymentBucket:
    name: ${file(./serverless-env.yml):deploy-bucket}

plugins:
  - serverless-webpack

package:
  excludeDevDependencies: true
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  scrape:
    name: '${self:service}'
    handler: src/scraper.handler
    environment:
      TZ: Asia/Toyko
      REGION: ap-northeast-1
      S3_BUCKET_NAME: ${file(./serverless-env.yml):scraper-bucket}
    # package:
    #   include: # Specify the directories and files which should be included in the deployment package for this specific function.
    #     # - src/**
    #     # - handler.js
    #  - ./src/index.js
    events:
      - schedule: cron(* * * * ? *) # every minutes
      # - cloudwatchLog:
      #     logGroup: '/aws/lambda/${self:service}'
  query:
    name: '${self:service}-query'
    handler: src/query.handler
    environment:
      # TZ: Asia/Toyko
      S3_REGION: ap-northeast-1
      S3_BUCKET_NAME: ${file(./serverless-env.yml):query-bucket}
    events:
      - http:
          path: '{proxy+}'
          method: GET
          cors: true
